services:
  - type: web
    name: loot-rush-game-server
    env: node
    plan: starter
    buildCommand: npm install && npm --prefix packages/shared run build && npm --prefix apps/game-server run build
    startCommand: npm --prefix apps/game-server run start
    autoDeploy: true
